_wandb:
    value:
        cli_version: 0.18.0
        m: []
        python_version: 3.10.10
        t:
            "1":
                - 1
                - 2
                - 3
                - 5
                - 11
                - 41
                - 49
                - 53
                - 55
                - 71
                - 80
                - 83
                - 98
            "3":
                - 4
                - 13
                - 23
                - 55
            "4": 3.10.10
            "5": 0.18.0
            "6": 4.45.2
            "8":
                - 5
            "12": 0.18.0
            "13": linux-x86_64
